on: 
  push:
    branches:
      - master
name: Production Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.toubkalit.com
        username: essabir@toubkalit.com
        password: ${{ secrets.ftp_password }}